spring.application.name=SB11_Security_JWT_Token

#DB config
spring.datasource.url= jdbc:postgresql://localhost:5432/DBName
spring.datasource.username=username
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
